#!/usr/bin/env bash
# Hello world Nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
args="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "26i $args" /etc/nginx/sites-available/default
sudo service nginx restart
