#!/usr/bin/env bash
# add Custom Header 'X-Served-By' with hostname as value

# install nginx
sudo apt-get -y install nginx
# update contents of index file
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

# redirects /redirect_me to another page
redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://github.com/stenwire/alx-system_engineering-devops/edit/main/0x0F-load_balancer/0-custom_http_response_header;\n\t}\n"
sudo sed -i "53s|.*|$redirect|" /etc/nginx/sites-enabled/default

# add custom header
sudo sed -i '52 a \\t\tadd_header X-Served-By $hostname;' /etc/nginx/sites-enabled/default

# restart nginx
sudo service nginx restart
