#!/usr/bin/env bash
# fix to setup nginx to listen to ::80

sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start

