#!/usr/bin/env bash
# usage of while loops in bash

counter=1

while [ $counter -le 10 ]
do
    echo "Best School"
    if [ $counter -eq 9 ]
    then
        echo "Hi"
    fi
    (( counter++ ))
done
