#!/usr/bin/env bash
# displays Best School 10 times but for the 9th iteration, displays Best School and then Hi on a new line

count=0
while [ "$count" -lt 10 ]; do
	echo "Best School"
	if [ "$count" -eq 8 ]
	then
	    echo "Hi"
	fi
	let count=count+1
done
