#!/bin/bash

limit=11
i=1

while (("$i" < "$limit")); do
    if (("$i" == 4)); then
        echo "bad luck"
    elif (("$i" == 8)); then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done