#!/usr/bin/env bash
# displays time

hour=0; minute=1

while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    while [ $minute -le 59 ]
    do
        echo "$minute"
        (( minute++ ))
    done
    minute=1
    (( hour++ ))
done
